"""initial_state_and_action_ledger

Revision: 4fbbd54df2ef
"""

import sqlalchemy as sa
from alembic import op

revision = "4fbbd54df2ef"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "approvals",
        sa.Column("operation_id", sa.String(length=36), nullable=False),
        sa.Column("payload_digest", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("decided_by", sa.String(length=160), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=120), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "operation_id"),
    )
    op.create_index(op.f("ix_approvals_tenant_id"), "approvals", ["tenant_id"], unique=False)
    op.create_table(
        "artifacts",
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=60), nullable=False),
        sa.Column("digest", sa.String(length=64), nullable=False),
        sa.Column("storage_key", sa.String(length=200), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=120), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_artifacts_task_id"), "artifacts", ["task_id"], unique=False)
    op.create_index(op.f("ix_artifacts_tenant_id"), "artifacts", ["tenant_id"], unique=False)
    op.create_table(
        "daily_budgets",
        sa.Column("day", sa.String(length=10), nullable=False),
        sa.Column("spent", sa.Integer(), nullable=False),
        sa.Column("reserved", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=120), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "day"),
    )
    op.create_index(
        op.f("ix_daily_budgets_tenant_id"), "daily_budgets", ["tenant_id"], unique=False
    )
    op.create_table(
        "documents",
        sa.Column("project", sa.String(length=80), nullable=False),
        sa.Column("source", sa.String(length=300), nullable=False),
        sa.Column("version", sa.String(length=160), nullable=False),
        sa.Column("body", sa.String(), nullable=False),
        sa.Column("allowed_subjects", sa.JSON(), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=120), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_documents_project"), "documents", ["project"], unique=False)
    op.create_index(op.f("ix_documents_tenant_id"), "documents", ["tenant_id"], unique=False)
    op.create_table(
        "grants",
        sa.Column("subject", sa.String(length=160), nullable=False),
        sa.Column("project", sa.String(length=80), nullable=False),
        sa.Column("environment", sa.String(length=40), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=120), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "subject", "project", "environment"),
    )
    op.create_index(op.f("ix_grants_tenant_id"), "grants", ["tenant_id"], unique=False)
    op.create_table(
        "inbox",
        sa.Column("provider", sa.String(length=60), nullable=False),
        sa.Column("external_id", sa.String(length=160), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("processed", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=120), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "provider", "external_id"),
    )
    op.create_index(op.f("ix_inbox_tenant_id"), "inbox", ["tenant_id"], unique=False)
    op.create_table(
        "operations",
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("step_key", sa.String(length=160), nullable=False),
        sa.Column("tool", sa.String(length=40), nullable=False),
        sa.Column("resource", sa.String(length=160), nullable=False),
        sa.Column("parameters", sa.JSON(), nullable=False),
        sa.Column("payload_digest", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("recovery_status", sa.String(length=30), nullable=True),
        sa.Column("external_id", sa.String(length=160), nullable=True),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("error", sa.String(length=160), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=120), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "task_id", "step_key"),
    )
    op.create_index(op.f("ix_operations_task_id"), "operations", ["task_id"], unique=False)
    op.create_index(op.f("ix_operations_tenant_id"), "operations", ["tenant_id"], unique=False)
    op.create_table(
        "outbox",
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("delivered", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=120), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "task_id"),
    )
    op.create_index(op.f("ix_outbox_tenant_id"), "outbox", ["tenant_id"], unique=False)
    op.create_table(
        "policies",
        sa.Column("disabled_tools", sa.JSON(), nullable=False),
        sa.Column("stopped", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=120), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id"),
    )
    op.create_index(op.f("ix_policies_tenant_id"), "policies", ["tenant_id"], unique=False)
    op.create_table(
        "reservations",
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("call_key", sa.String(length=160), nullable=False),
        sa.Column("maximum", sa.Integer(), nullable=False),
        sa.Column("actual", sa.Integer(), nullable=True),
        sa.Column("day", sa.String(length=10), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=120), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "task_id", "call_key"),
    )
    op.create_index(op.f("ix_reservations_tenant_id"), "reservations", ["tenant_id"], unique=False)
    op.create_table(
        "task_events",
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=60), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=120), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "task_id", "sequence"),
    )
    op.create_index(op.f("ix_task_events_task_id"), "task_events", ["task_id"], unique=False)
    op.create_index(op.f("ix_task_events_tenant_id"), "task_events", ["tenant_id"], unique=False)
    op.create_table(
        "tasks",
        sa.Column("request_key", sa.String(length=160), nullable=False),
        sa.Column("request_digest", sa.String(length=64), nullable=False),
        sa.Column("principal", sa.String(length=160), nullable=False),
        sa.Column("contract", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("result", sa.String(length=30), nullable=True),
        sa.Column("waiting_reason", sa.String(length=120), nullable=True),
        sa.Column("cancelled", sa.Boolean(), nullable=False),
        sa.Column("taken_over", sa.Boolean(), nullable=False),
        sa.Column("deadline", sa.DateTime(timezone=True), nullable=False),
        sa.Column("spent", sa.Integer(), nullable=False),
        sa.Column("reserved", sa.Integer(), nullable=False),
        sa.Column("next_sequence", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=120), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "request_key"),
    )
    op.create_index(op.f("ix_tasks_tenant_id"), "tasks", ["tenant_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tasks_tenant_id"), table_name="tasks")
    op.drop_table("tasks")
    op.drop_index(op.f("ix_task_events_tenant_id"), table_name="task_events")
    op.drop_index(op.f("ix_task_events_task_id"), table_name="task_events")
    op.drop_table("task_events")
    op.drop_index(op.f("ix_reservations_tenant_id"), table_name="reservations")
    op.drop_table("reservations")
    op.drop_index(op.f("ix_policies_tenant_id"), table_name="policies")
    op.drop_table("policies")
    op.drop_index(op.f("ix_outbox_tenant_id"), table_name="outbox")
    op.drop_table("outbox")
    op.drop_index(op.f("ix_operations_tenant_id"), table_name="operations")
    op.drop_index(op.f("ix_operations_task_id"), table_name="operations")
    op.drop_table("operations")
    op.drop_index(op.f("ix_inbox_tenant_id"), table_name="inbox")
    op.drop_table("inbox")
    op.drop_index(op.f("ix_grants_tenant_id"), table_name="grants")
    op.drop_table("grants")
    op.drop_index(op.f("ix_documents_tenant_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_project"), table_name="documents")
    op.drop_table("documents")
    op.drop_index(op.f("ix_daily_budgets_tenant_id"), table_name="daily_budgets")
    op.drop_table("daily_budgets")
    op.drop_index(op.f("ix_artifacts_tenant_id"), table_name="artifacts")
    op.drop_index(op.f("ix_artifacts_task_id"), table_name="artifacts")
    op.drop_table("artifacts")
    op.drop_index(op.f("ix_approvals_tenant_id"), table_name="approvals")
    op.drop_table("approvals")
    # ### end Alembic commands ###
